language: cpp
compiler:
- ": foo bar"

script:
- cat ~/.bashrc

after_success:
- which rvm
- rvm info

before_deploy:
- source "$HOME/.rvm/scripts/rvm"
- rvm use 2.2 --binary --install

deploy:
  provider: script
  repo: mroch/travis-test
  script: bash -e deploy.sh
  skip_cleanup: true
